version: '2'

services: 

  web:
    image: nginx
    ports:
    - 9090:80
  
  database:
    image: couchdb   
    ports:
    - 8040:80
 
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /path/to/app:/app
